In [23]:
import pandas as pd
import os

In [25]:
player_stats_df = pd.read_csv('data/totals_stats.csv')
player_stats_df

,Season,Age,Team,Lg,G,MP,FG,FGA,FG%,3P,...,PF,PTS,Trp-Dbl,Awards,player_id,Pos,GS,3P%,STL,BLK
0,1970-71,26,PTC,ABA,9.0,57.0,3.0,12.0,0.250,0.0,...,16.0,13.0,0.0,NaN,lauriha01,NaN,NaN,NaN,NaN,NaN
1,2010-11,24,MIN,NBA,42.0,419.0,55.0,154.0,0.357,17.0,...,44.0,160.0,0.0,NaN,haywala01,SF,0.0,0.283,12.0,7.0
2,2011-12,25,OKC,NBA,26.0,141.0,13.0,38.0,0.342,4.0,...,18.0,37.0,0.0,NaN,haywala01,SF,0.0,0.286,3.0,1.0
3,2012-13,26,MIN,NBA,4.0,31.0,2.0,10.0,0.200,0.0,...,3.0,10.0,0.0,NaN,haywala01,SF,0.0,0.000,2.0,0.0
4,2019-20,23,SAC,NBA,36.0,232.0,35.0,84.0,0.417,9.0,...,17.0,89.0,0.0,NaN,jamesju01,SF,0.0,0.310,6.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35691,2000-01,24,CHH,NBA,67.0,1201.0,216.0,407.0,0.531,2.0,...,66.0,498.0,0.0,NaN,robined01,SF,6.0,0.500,50.0,32.0
35692,2001-02,25,CHI,NBA,29.0,653.0,112.0,247.0,0.453,2.0,...,35.0,262.0,0.0,NaN,robined01,SF,12.0,0.400,23.0,11.0
35693,2002-03,26,CHI,NBA,64.0,1355.0,155.0,315.0,0.492,3.0,...,120.0,364.0,0.0,NaN,robined01,SF,18.0,0.214,62.0,13.0
35694,2003-04,27,CHI,NBA,51.0,1024.0,157.0,326.0,0.482,1.0,...,57.0,343.0,0.0,NaN,robined01,SF,4.0,0.200,33.0,10.0
35695,1988-89,22,NJN,NBA,37.0,307.0,50.0,102.0,0.490,0.0,...,38.0,129.0,0.0,NaN,jonesbi01,PF,0.0,0.000,17.0,6.0